config/routes.rb
Rails.application.routes.draw do
  get 'documents/index'

  get 'documents/new'

  get 'documents/create'

  get 'documents/destroy'
  get '/allnotices'=> 'home#allnotices'
  get '/download/:id' => 'documents#download'
  devise_for :members, :controllers =>{registrations: 'members/registrations'}
  root :to=> 'home#homepage'
delete 'members/sign_out' => "devise/sessions#destroy"
get '/homepage'=> 'home#homepage'
#get '/tutorials'=> 'temp#tutorials'
get '/tutorials'=> 'documents#index'
get '/allfacultydetails'=> 'home#allfacultydetails'
post '/contactdetails'=> 'home#contactdetails'
get '/contactadmin'=>'home#contactadmin'
post '/noticeupdate'=> 'home#noticeupdate'
get '/notice'=>'home#notice'
get '/updatefaculty'=>'home#updatefaculty'
post '/updatefacultydetails'=> 'home#updatefacultydetails'
get '/facultycontact/:id'=> 'home#facultycontact'
post '/facultycontactdetails'=> 'home#facultycontactdetails'
resources :documents, only: [:index, :new, :create, :destroy]
end

app/models/document.rb
class Document < ActiveRecord::Base
	 mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
  	validates :attachment, presence: true  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
  	@documents = Document.all
  end

  def new
  	@document = Document.new
  end

  def create
  	@document = Document.new(document_params)
      if @document.save
      	File.open(Rails.root.join('public','FilesUploaded',@document.name),'wb') do |f|
      		f.write(@document.attachment.read)
      	end
         redirect_to documents_path, notice: "The document #{@document.name} has been uploaded."
      else
         render "new"
      end
  end

  def destroy
  	@document = Document.find(params[:id])
      @document.destroy
      redirect_to documents_path, notice:  "The document #{@document.name} has been deleted."
  end

  def download
  	filetodownload= params[:id]
  	send_file Rails.root.join('public','FilesUploaded',filetodownload)
  end

  private
      def document_params
      params.require(:document).permit(:name, :attachment)
   end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/index.html.erb
<html>
<h2 align="center" >Docs List</h2>
<body style="background:linear-gradient(#FF9966,#FFCCCC);">
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

 <% if (current_member.person!= 'Student')%>

<br />
<div align="right" style="margin-right: 3%;">
<%= link_to "New Document", new_document_path, class: "btn btn-primary" %></div>
<%end%>
<table class = "table table-bordered table-striped table-hover" align="center" style="width: 80%;background-color: white">
   <thead>.
      <tr style="background-color: grey;font-size: 17px;">
         <th>Name</th>
        
         <th>Download Link</th>
          <% if (current_member.person!= 'Student')%>
         <th>Delete Link </th>
         <%end%>
         
      </tr>
   </thead>
   
   <tbody>
      <% @documents.each do |document| %>
         
         <tr>
            <td><%= document.name %></td>
            <td><%= link_to "Download","/download/#{document.name}",method: :get, class: "btn btn-primary" %></td>
            <% if (current_member.person!= 'Student')%>
            <td><%= button_to "Delete",  document, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{document.name}?" %></td>
            <%end%>
         </tr>
         
      <% end %>
   </tbody>
   
</table>
</body>
</html>
<style type="text/css">

</style>

app/views/documents/new.html.erb
<h3>Upload here</h3>

<% if !@document.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @document.errors.full_messages.each do |msg| %>
            <li style="color:red"><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well" style="padding: 5%;" >
   <%= form_for @document, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br/><br/>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <br/>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>